apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: keycloak 
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
