---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-config
    creationPolicy: Owner
  dataFrom:
  - key: cnoe/keycloak/config
    property: provider-key-property
    
---
#External Postgres JDBC and pwd details 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: postgresql-config
    creationPolicy: Owner
  data:
    - secretKey: KC_DB_URL
      remoteRef:
        key: postgresql-connection-details-v2
        property: jdbcurl
    - secretKey: KC_DB_URL_HOST
      remoteRef:
        key: postgresql-connection-details-v2
        property: dbType
    - secretKey: KC_DB
      remoteRef:
        key: postgresql-connection-details-v2
        property: dbType

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: postgresql-config
    creationPolicy: Owner
  data:
    - secretKey: KC_DB_URL
      remoteRef:
        key: cnoe/keycloak/config
        property: POSTGRES_DB
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: cnoe/keycloak/config
        property: POSTGRES_PASSWORD
    - secretKey: POSTGRES_USER
      remoteRef:
        key: cnoe/keycloak/config
        property: POSTGRES_USER
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-user-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-user-config
    creationPolicy: Owner
  data:
    - secretKey: user1-password
      remoteRef:
        key: cnoe/keycloak/config
        property: user1-password
