---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-config
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: cnoe/keycloak/config
    
    
---
#External Postgres JDBC and pwd details 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: postgresql-config
    creationPolicy: Owner
  dataFrom:
  - extract: 
      key: postgresql-connection-details-v2
   


---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-user-config
  namespace: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: keycloak
    kind: SecretStore
  target:
    name: keycloak-user-config
    creationPolicy: Owner
  data:
    - secretKey: user1-password
      remoteRef:
        key: cnoe/keycloak/config
        property: user1-password
