apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-config
          configMap:
            name: keycloak-config
      containers:
        - name: keycloak
          envFrom:
            - secretRef:
                name: keycloak-config
          args:
            - start
          volumeMounts:
            - name: keycloak-config
              mountPath: "/opt/keycloak/conf"
              readOnly: true
